include:
  - board: nrf52840
    shield: settings_reset
  - board: mouse_corne_left
    shield: nice_view
  - board: mouse_corne_right
    shield: nice_view
  - board: mouse_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: mouse_corne_studio_left